### ISSUE TITLE
汉化 sao ui

### ISSUE THREAD

**Issue by MutoMagic** [MutoMagic/mc-private-server#1]
附件里有原文件以及部分汉化的文件，由于原作者无限推延，需要跟进版本。

[en_US.lang.txt](https://github.com/MutoMagic/mc-private-server/files/767157/en_US.lang.txt)

[zh_CN.lang.txt](https://github.com/MutoMagic/mc-private-server/files/767155/zh_CN.lang.txt)

**Comment by csga31971** [comment]
[zh_CN.lang.txt](https://github.com/MutoMagic/mc-private-server/files/768339/zh_CN.lang.txt)

不确定的地方在# Options - Effects下面 一共三处

**Comment by MutoMagic** [comment]
@csga31971 在学姐的帮助下 将不确定的地方补全了

[zh_CN.lang.txt](https://github.com/MutoMagic/mc-private-server/files/769079/zh_CN.lang.txt)

**Comment by MutoMagic** [comment]
optionCursorToggle= 切换光标移动方式 > 界面随鼠标移动

@csga31971 在学姐的帮助下完成了不确定的地方
再此感谢所有参与汉化的人员，以及原作者在mcbbs中提供的汉化原型。
[zh_CN.lang.txt](https://github.com/MutoMagic/mc-private-server/files/769092/zh_CN.lang.txt)

2017/02/12 更新 修复了部分翻译错误
[zh_CN.lang.txt](https://github.com/MutoMagic/mc-private-server/files/769154/zh_CN.lang.txt)
